[book]
authors = ["nasso"]
language = "en"
multilingual = false
title = "OpenGL Workshop"
site-url = "/opengl-workshop/"
cname = "nasso.dev"

[output.html]
additional-css = ["custom.css"]
preferred-dark-theme = "ayu"
